### ISSUE TITLE
doesn't build on RHEL 5.5

### ISSUE THREAD

**Issue by janl** [jhs/build-couchdb#17]
I'm using RHEL 5.5 (no choice due to IT rules).  The versions are:

$ ruby --version
ruby 1.8.6 (2007-09-24 patchlevel 111) [x86_64-linux]
$ rake --version
rake, version 0.8.7

Not sure where to report this, or how to get help.  I'm trying to install using the instructions at http://www.couch.io/get#build.  When I type "rake", I get an error.  I've installed all packages as specified in the instructions (gcc gcc-c++ libtool libcurl-devel zlib-devel openssl-devel rubygem-rake).

Here's what happens:

$ pwd
/users/sdrach/build-couchdb
$ ls -a
.  ..  dependencies  env.sh  .git  .gitignore  .gitmodules  Rakefile  README.md  tasks  TODO
$ rake
(in /users/sdrach/build-couchdb)
rake aborted!
undefined method `[]' for nil:NilClass

(See full trace by running task with --trace)
